#!/usr/bin/env python
"""
If the numbers 1 to 5 are written out in words: one, two, three, four,
five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out
in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and
forty-two) contains 23 letters and 115 (one hundred and fifteen) contains
20 letters. The use of "and" when writing out numbers is in compliance with
British usage.
"""
#Reference
"""
one      ten            twenty
two      eleven         thirty
three    twelve         forty
four     thirteen       fifty
five     fourteen       sixty
six      fifteen        seventy
seven    sixteen        eighty
eight    seventeen      ninety
nine     eighteen       hundredand
         nineteen       thousand
"""
total = 0
for i in range(1,1001):

    #third digit
    if i >= 100:
        if (i % 1000) // 100 == 0:
            total += 11 #onethousand
        elif (i % 1000) // 100 in [1, 2, 6]:
            total += 10
        elif (i % 1000) // 100 in [4, 5, 9]:
            total += 11
        else:
            total += 12

        if i % 100 != 00:
            total += 3

    if i % 100 not in range(10,20):

        #first digit
        if i % 10 == 0:
            total = total
        elif i % 10 in [1, 2, 6]:
            total += 3
        elif i % 10 in [4, 5, 9]:
            total += 4
        else:
            total += 5

        #second digit
        if i >= 20:
            if (i % 100) // 10 == 0:
                total = total
            elif (i % 100) // 10 in [2, 3, 8, 9]:
                total += 6
            elif (i % 100) // 10 in [4, 5, 6]:
                total += 5
            else:
                total += 7

    else: #if teen
        if i % 10 == 0:
            total += 3
        elif i % 10 in [3, 4, 8, 9]:
            total += 8
        elif i % 10 in [1, 2]:
            total += 6
        elif i % 10 in [5, 6]:
            total += 7
        else:
            total += 9

print(total)
