#!/usr/bin/env python
"""
A Pythagorean triplet is a set of three natural numbers, a < b < c,
for which,

    a² + b² = c²

For example, 3² + 4² = 9 + 16 = 25 = 5².

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
"""
n = 1
m = 2
run = True
while run:
    a = m**2 - n**2
    b = 2 * m * n
    c = m**2 + n**2
    if a + b + c > 1000:
        n += 1
        m = n + 1
    elif a + b + c == 1000:
        run = False
    else:
        m += 1
print(a * b * c)
