#!/usr/bin/env python
"""
2¹⁵ = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 2¹⁰⁰⁰?
"""
x = 2**1000
a = 0
for i in str(x):
    a += int(i)
print(a)
