#!/usr/bin/env python
"""
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see
that the 6th prime is 13.

What is the 10 001st prime number?
"""
#http://www.daniweb.com/software-development/python/code/216880/check-if-a-number-is-a-prime-number-python
def isprime(n):
    "Check if integer n is a prime"
    n = abs(int(n))
    if n < 2:
        return False
    if n == 2:
        return True
    if not n & 1:
        return False
    for x in range(3, int(n**0.5)+1, 2):
        if n % x == 0:
            return False
    return True

def main():
    x = 1
    n = 0
    while n < 10001:
        x += 1
        if isprime(x):
            n += 1
    return x

print(main())
