#!/usr/bin/env python
"""
You are given the following information, but you may prefer to do some
research for yourself.

  - 1 Jan 1900 was a Monday.
  - Thirty days has September,
    April, June and November.
    All the rest have thirty-one,
    Saving February alone,
    Which has twenty-eight, rain or shine.
    And on leap years, twenty-nine.
  - A leap year occurs on any year evenly divisible by 4, but not on a
    century unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth 
century (1 Jan 1901 to 31 Dec 2000)?
"""
total = 0
days = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334]
leap = [0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335]
def isleap(year):
    if year % 100 == 0 and year % 400 == 0:
        return leap
    elif year % 100 != 0 and year % 4 == 0:
        return leap
    else:
        return days

for year in range(1901, 2001):
    #http://userpages.wittenberg.edu/bshelburne/Comp150/DayOfWeek.htm
    a = (year - 1901) % 28
    b = a // 4
    w = (2 + a + b) % 7
    for day in isleap(year):
        if (day + w) % 7 == 0:
            total += 1

print(total)
