#!/usr/bin/env python
"""
2520 is the smallest number that can be divided by each of the numbers from
1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the
numbers from 1 to 20?
"""
x=20
a=0
while a == 0:
    if x % 11 == 0 and \
       x % 12 == 0 and \
       x % 13 == 0 and \
       x % 14 == 0 and \
       x % 15 == 0 and \
       x % 16 == 0 and \
       x % 17 == 0 and \
       x % 18 == 0 and \
       x % 19 == 0 and \
       x % 20 == 0:
        a = x
    x += 20
print(a)
