#!/usr/bin/env python
"""
The series, 1¹ + 2² + 3³ + ... + 10¹⁰ = 10405071317.

Find the last ten digits of the series, 1¹ + 2² + 3³ + ... + 1000¹⁰⁰⁰.
"""
total = 0
for i in range(1, 1001):
    total += i**i

print(total % 10**10)
